// APIS

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const ENABLE_LOADING = 'ENABLE_LOADING';
export const DISABLE_LOADING = 'DISABLE_LOADING';

// PROJECT TYPES

export const ADD_PROJECT = "ADD_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"
export const UPDATE_PROJECT = "UPDATE_PROJECT"
export const FETCHED_PROJECT = "FETCHED_PROJECT"
export const FETCHED_MORE_PROJECT = "FETCHED_MORE_PROJECT"
export const UPDATE_PROJECT_FILTERS = "UPDATE_PROJECT_FILTERS"
export const UPDATE_PROJECT_CATEGORY = "UPDATE_PROJECT_CATEGORY"
export const UPDATE_RATING = "UPDATE_RATING"
export const SET_DATA = "SET_DATA"

// SETTING TYPES

export const DARK = "DARK"
export const LIGHT = "LIGHT"
export const LANGUAGE = "LANGUAGE"
export const NONEPOPUP = "NONEPOPUP"
export const SHOWNOTOFICATION = "SHOWNOTOFICATION"
export const SHOWSETTING = "SHOWSETTING"
export const SHOWPROFILE = "SHOWPROFILE"

// AUTH

export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER = 'SET_USER';
export const VERIFIED = 'VERIFIED';
export const USER_NONE = 'USER_NONE';
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"


// ERROR handling

export const SETERROR = 'SETERROR';

export const ERROR_SIGNUP_VERIFY = 'SIGNUP_VERIFY';
export const ERROR_UNKNOWN = 'UNKNOWN';

// CATEGORIES

export const SET_CATEGORIES = 'SET_CATEGORIES';

// PROFILE
export const SET_PROFILE_DATE = 'SET_PROFILE_DATE';

// LOCAL STORAGE
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

// SEND NOTIFICATIONS
export const SEND_NOTIFICATIONS_TO_ALL_USERS = 'SEND_NOTIFICATIONS_TO_ALL_USERS';
export const SEND_NOTIFICATIONS_TO_SELECTED_USERS = 'SEND_NOTIFICATIONS_TO_SELECTED_USERS';

// Message
export const SET_CHATS = 'SET_CHATS';
export const OPEN_CHAT = 'OPEN_CHAT';
export const CLOSE_CHAT = 'CLOSE_CHAT';
export const RESET_CHAT = 'RESET_CHAT';
export const SET_MESSAGES_LIST = 'SET_MESSAGES_LIST';

////////////// KEYS OF APP ///////////////////
export const KEY_AUTH = 'SET_AUTH';
export const KEY_SETTINGS = 'KEY_SETTINGS';
export const KEY_AUTH_LOGOUT = 'KEY_AUTH_LOGOUT';
export const KEY_NOTIFICATION = 'OPEN_CHAT';
export const KEY_MESSAGES = 'CLOSE_CHAT';
export const KEY_MYPROFILE = 'RESET_CHAT';
// CyCLES
export const KEY_PRODUCER = 'KEY_PRODUCER';
export const KEY_COPY_RIGHTS = 'KEY_COPY_RIGHTS';
export const KEY_PORTFOLIO_POST = 'KEY_PORTFOLIO_POST';
export const KEY_STUDIO_BOOKING = 'KEY_STUDIO_BOOKING';
// CyCLES
export const KEY_PRODUCER_ANALYSIS = 'KEY_PRODUCER_ANALYSIS';
export const KEY_COPY_RIGHTS_ANALYSIS = 'KEY_COPY_RIGHTS_ANALYSIS';
export const KEY_PROJECT_ANALYSIS = 'KEY_PROJECT_ANALYSIS';
export const KEY_RENTAL_ANALYSIS = 'KEY_RENTAL_ANALYSIS';
export const KEY_CONTRACT_ANALYSIS = 'KEY_CONTRACT_ANALYSIS';
// CATEGORY
export const KEY_CATEGORY = 'KEY_CATEGORY';
export const KEY_CATEGORY_ID = 'KEY_CATEGORY_ID';
export const KEY_CATEGORY_CREATE = 'KEY_CATEGORY_CREATE';
export const KEY_CATEGORY_DELETE = 'KEY_CATEGORY_DELETE';
// KEY_TERMS
export const KEY_TERMS = 'KEY_TERMS';
// KEY_TERMS
export const KEY_TICKET = 'KEY_TICKET';
// KEY_USERS
export const KEY_USERS = 'KEY_USERS';
// KEY_CHAT
export const KEY_CHAT_GETALL = 'KEY_CHAT_GETALL';
export const KEY_CHAT = 'KEY_CHAT';
export const KEY_CHAT_SEND = 'KEY_CHAT_SEND';
// KEY_ROLE
export const KEY_CREATE_ROLE = 'KEY_CREATE_ROLE';
export const KEY_DELETE_ROLE = 'KEY_DELETE_ROLE';
export const KEY_GET_ROLES = 'KEY_GET_ROLES';
export const KEY_GET_ROLE_BY_ID = 'KEY_GET_ROLE_BY_ID';
export const KEY_UPDATE_ROLE = 'KEY_UPDATE_ROLE';
// KEY_PLATFORM
export const KEY_CREATE_PLATFORM = 'KEY_CREATE_PLATFORM';
export const KEY_DELETE_PLATFORM = 'KEY_DELETE_PLATFORM';
export const KEY_GET_PLATFORMS = 'KEY_GET_PLATFORMS';
export const KEY_GET_PLATFORM_BY_ID = 'KEY_GET_PLATFORM_BY_ID';
export const KEY_UPDATE_PLATFORM = 'KEY_UPDATE_PLATFORM';
// KEY_PLAN
export const KEY_CREATE_PLAN = 'KEY_CREATE_PLAN';
export const KEY_DELETE_PLAN = 'KEY_DELETE_PLAN';
export const KEY_GET_PLANS = 'KEY_GET_PLANS';
export const KEY_GET_PLAN_BY_ID = 'KEY_GET_PLAN_BY_ID';
export const KEY_UPDATE_PLAN = 'KEY_UPDATE_PLAN';
// KEY_RANK
export const KEY_CREATE_RANK = 'KEY_CREATE_RANK';
export const KEY_DELETE_RANK = 'KEY_DELETE_RANK';
export const KEY_GET_RANKS = 'KEY_GET_RANKS';
export const KEY_GET_RANK_BY_ID = 'KEY_GET_RANK_BY_ID';
export const KEY_UPDATE_RANK = 'KEY_UPDATE_RANK';
// KEY_COUPON
export const KEY_CREATE_COUPON = 'KEY_CREATE_COUPON';
export const KEY_DELETE_COUPON = 'KEY_DELETE_COUPON';
export const KEY_GET_COUPONS = 'KEY_GET_COUPONS';
export const KEY_GET_COUPON_BY_ID = 'KEY_GET_COUPON_BY_ID';
export const KEY_UPDATE_COUPON = 'KEY_UPDATE_COUPON';
// KEY_COMPLAINT
export const KEY_GET_COMPLAINTS = 'KEY_GET_COMPLAINTS';
export const KEY_GET_COMPLAINT_BY_ID = 'KEY_GET_COMPLAINT_BY_ID';
export const KEY_UPDATE_COMPLAINT = 'KEY_UPDATE_COMPLAINT';
// KEY_REVIEWS
export const KEY_GET_REVIEWS = 'KEY_GET_REVIEWS'
// KEY_ADMIN
export const KEY_CREATE_ADMIN = 'KEY_CREATE_ADMIN';
export const KEY_UPDATE_ADMIN = 'KEY_UPDATE_ADMIN';
export const KEY_BLOCK_ADMIN = 'KEY_BLOCK_ADMIN';
export const KEY_UN_BLOCK_ADMIN = 'KEY_UN_BLOCK_ADMIN';
// New constant
export const KEY_GET_CANCELLED_CONTRACTS = 'KEY_GET_CANCELLED_CONTRACTS';
